### ISSUE TITLE
Finish keyboard install page (aka universal link infrastructure) for macOS,Android,iOS

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/api.keyman.com#109]
Finish keyboard install page (aka universal link infrastructure) for:

- [x] macOS (fix: keymanapp/keyman.com#172)
- [x] Android (fix: keymanapp/keyman.com#185)
- [x] iOS (fix: keymanapp/keyman.com#184)

_Originally posted by @mcdurdin in https://github.com/keymanapp/api.keyman.com/issues/87#issuecomment-669693845_

**Comment by mcdurdin** [comment]
@darcywong00 can you advise on Android requirements for the Install page (e.g. https://keyman-staging.com/keyboards/install/khmer_angkor) when Keyman is not installed?

@jahorton can you advise on iOS requirements for the Install page (e.g. https://keyman-staging.com/keyboards/install/khmer_angkor) when Keyman is not installed?

**Comment by jahorton** [comment]
Well, for starts... that formatting.

<img width="559" alt="Screen Shot 2020-09-22 at 1 30 44 PM" src="https://user-images.githubusercontent.com/25213402/93850229-daf6d880-fcd7-11ea-8632-8e87c2012b7c.png">

The basic install link checks out from live devices.  (Oddly, Safari thinks it's invalid every time I try to test it in the Simulator.)

Long-pressing the second link brings up the "Open in Keyman" command to install the package.  Weird that it wasn't launching Keyman without it; maybe that bit of universal link stuff never got fully completed properly?  At any rate, that should be all that would be needed; the 1 + 2 would cover it.
